class DomainError(Exception):
    ...

class AccountNotFound(DomainError):
    ...

class InsufficientFunds(DomainError):
    ...

class CurrencyMismatch(DomainError):
    ...
    
class AccountAlreadyExists(DomainError):
    ...

class TransactionAlreadyExists(DomainError):
    ...